rootProject.name = "prog-avanzada3"
include("ejemplo01")
include("ejemplo02")
include("prueba")
include("correccion")
include("listas")
include("listas")
include("recursion")
include("tarea_arbol")
include("merge")
include("repaso")
include("repaso2")
